axis_linear: 4          # Right stick up/down
scale_linear: 0.3
scale_linear_turbo: 1

axis_angular: 3         # Right stick left/right
scale_angular: 1

enable_button: 5        # RB shoulder button
enable_turbo_button: 4  # LB shoulder button
