scan_filter_chain:
- name: angle_depth
  type: laser_filters/LaserScanSectorFilter
  params:
    angle_min: 2.54
    angle_max: -2.54
    range_min: 0.2
    range_max: 2.0
    clear_inside: true
#- name: shadows
#  type: laser_filters/ScanShadowsFilter
#  params:
#    min_angle: 10
#    max_angle: 170
#    neighbors: 20
#    window: 1

