tank_setup_tf_node:
    tfRate: 20

    laserTfX: 0.06
    laserTfY: 0
    laserTfZ: 0.20
    laserTfRoll: 0
    laserTfPitch: 0
    # Rotate laser data 180 degree to correct laser rader angle.
    laserTfYaw: 3.14159265358979323846264338327950288

    depthTfEnabled: true
    depthTfX: 0.135
    depthTfY: 0
    depthTfZ: 0.17
    depthTfRoll: 0
    depthTfPitch: 0
    depthTfYaw: 0
