odom_model_type: diff-corrected
odom_frame_id: odom
odom_alpha1: 0.005
odom_alpha2: 0.005
odom_alpha3: 0.010
odom_alpha4: 0.005
odom_alpha5: 0.003
min_particles: 200
max_particles: 5000
kld_err: 0.05
kld_z: 0.99
laser_max_beams: 12
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_lambda_short: 0.1
laser_model_type: likelihood_field
#laser_model_type: beam
laser_likelihood_max_dist: 2.0
update_min_d: 0.1
update_min_a: 0.1
resample_interval: 1
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1
transform_tolerance: 0.5
gui_publish_rate: 2.0

initial_pose_x: 13.364
initial_pose_y: 23.414
initial_pose_z: 0.0
