footprint: [[-0.22, -0.12], [-0.22, 0.12], [0.18, 0.12], [0.18, -0.12]]
footprint_padding: 0.02

max_obstacle_height: 0.50

inflation_layer:
    enabled: true
    inflation_radius:       0.50
    cost_scaling_factor:    15.0

obstacle_layer:
    enabled: true
    max_obstacle_height:    0.50
    origin_z:               0.0
    z_resolution:           0.2
    z_voxels:               2
    unknown_threshold:      15
    mark_threshold:         0
    combination_method:     1
    track_unknown_space:    true
    publish_voxel_map:      false
    observation_sources:    laser_scan_sensor depth_laser_scan_sensor
    laser_scan_sensor:
        data_type: LaserScan
        topic: scan
        sensor_frame: base_laser
        marking: true
        clearing: true
        min_obstacle_height: 0.00
        max_obstacle_height: 0.25
        obstacle_range:      6
        raytrace_range:      10
        inf_is_valid:        true
        expected_update_rate: 8.0
    depth_laser_scan_sensor:
        data_type: LaserScan
        topic: depth_laser_scan
        marking: true
        clearing: true
        min_obstacle_height: 0.00
        max_obstacle_height: 0.25
        obstacle_range:      2
        raytrace_range:      3
        expected_update_rate: 5.0
#    depth_scan_sensor:
#        data_type: PointCloud2
#        topic: /camera/depth/color/points
#        marking: true
#        clearing: true
#        min_obstacle_height: 0.00
#        max_obstacle_height: 1.00
#        obstacle_range:      6
#        raytrace_range:      10
#        expected_update_rate: 15.0

static_layer:
    enabled: true
