footprint: [[-0.22,-0.13], [-0.22,0.13], [0.18,0.13], [0.22,0.0], [0.18,-0.13]]
footprint_padding: 0.02

max_obstacle_height: 0.50

inflation_layer:
    enabled: true
    inflation_radius:       0.8
    cost_scaling_factor:    6.0

static_layer:
    enabled: true
    subscribe_to_updates: true
    track_unknown_space: true

obstacle_layer:
    enabled: true
    max_obstacle_height:    0.50
    origin_z:               0.0
    z_resolution:           0.2
    z_voxels:               2
    unknown_threshold:      15
    mark_threshold:         0
    combination_method:     1
    track_unknown_space:    true
    publish_voxel_map:      false
    observation_sources:    laser_scan_sensor depth_laser_scan_sensor
    laser_scan_sensor:
        data_type: LaserScan
        topic: scan_filtered
        sensor_frame: base_laser
        marking: true
        clearing: true
        min_obstacle_height: 0.00
        max_obstacle_height: 0.30
        obstacle_range:      8
        raytrace_range:      8
        inf_is_valid:        true
        expected_update_rate: 8.0
    depth_laser_scan_sensor:
        data_type: LaserScan
        topic: depth_laser_scan
        marking: true
        clearing: true
        min_obstacle_height: 0.00
        max_obstacle_height: 0.25
        obstacle_range:      2
        raytrace_range:      2
        inf_is_valid:        true
        expected_update_rate: 10.0
#    depth_scan_sensor:
#        data_type: PointCloud2
#        topic: /camera/depth/color/points
#        marking: true
#        clearing: true
#        min_obstacle_height: 0.00
#        max_obstacle_height: 1.00
#        obstacle_range:      6
#        raytrace_range:      10
#        expected_update_rate: 15.0
