obstacle_range: 10
raytrace_range: 10
footprint: [[-0.28, -0.15], [-0.28, 0.15], [0.22, 0.15], [0.22, -0.15]]
inflation_radius: 1.5
cost_scaling_factor: 3.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}

