#base_local_planner: "base_local_planner/TrajectoryPlannerROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

#base_global_planner: "navfn/NavfnROS"
base_global_planner: "global_planner/GlobalPlanner"
#base_global_planner: "carrot_planner/CarrotPlanner"

planner_frequency: 1.0
planner_patience: 5.0

controller_frequency: 10.0
controller_patience: 6.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

shutdown_costmaps: false
