#base_local_planner: "base_local_planner/TrajectoryPlannerROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

#base_global_planner: "navfn/NavfnROS"
base_global_planner: "global_planner/GlobalPlanner"
#base_global_planner: "carrot_planner/CarrotPlanner"

planner_frequency: 0.5
planner_patience: 5.0
max_planning_retries: -1

controller_frequency: 10.0
controller_patience: 6.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

shutdown_costmaps: false

recovery_behavior_enabled: true
clearing_rotation_allowed: false
recovery_behaviors:
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'move_slow_and_clear'
    type: 'move_slow_and_clear/MoveSlowAndClear'

super_conservative_reset:
  reset_distance: 5.0

conservative_reset:
  reset_distance: 3.0

aggressive_reset:
  reset_distance: 0.8

move_slow_and_clear:
  clearing_distance: 0.5
  limited_trans_speed: 0.2
  limited_rot_speed: 0.4
  limited_distance: 0.5
