TrajectoryPlannerROS:
    acc_lim_x: 2.5
    acc_lim_y: 2.5
    acc_lim_theta: 3.2

    max_vel_x: 0.5
    min_vel_x: 0.2
    max_vel_theta: 1.0
    min_vel_theta: -1.0
    min_in_place_vel_theta: 0.5

    escape_vel: -0.3

    holonomic_robot: false

    yaw_goal_tolerance: 0.05
    xy_goal_tolerance: 0.30
    latch_xy_goal_tolerance: true

    sim_time: 1.0
    #sim_granularity: 0.025
    #angular_sim_granularity: 0.025
    #vx_samples: 5
    #vtheta_samples: 20

    meter_scoring: true
    pdist_scale: 1.2
    gdist_scale: 0.8
    occdist_scale: 1.60

